### ISSUE TITLE
Convert html symbols back to their ascii characters

### ISSUE THREAD

**Issue by bowdens** [bowdens/tweet-simulator#6]
The twitter API automatically converts HTML symbols like <>& to sanitized versions `&lt; &gt; &amp;`

Because of this, if the twitter bot tries to replicate tweets with those characters, they will be tweeted as their sanitized versions. Either before the characters are added, or after the sentence is generated, the bot should convert the sanitized versions into the original ascii characters.

**Comment by TPreece101** [comment]
@bowdens I will have a go at this if you don't mind.

**Comment by bowdens** [comment]
Go ahead @TPreece101
